# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-home-task-LS"
client_id = "b7a0df9ef326a13f52dee338615b94cc"
application_url = "https://acres-sms-previous-february.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://acres-sms-previous-february.trycloudflare.com/auth/callback",
  "https://acres-sms-previous-february.trycloudflare.com/auth/shopify/callback",
  "https://acres-sms-previous-february.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-104.myshopify.com"
